// src/lib/courseData.ts

export const chapters = [
    {
        id: 0,
        href: "/introduction",
        num: "מבוא",
        label: "ברוכים הבאים",
        title: "מבוא: להסיר את הווילון מעל ה-AI",
        description: "המודלים לא עושים קסמים. הם עובדים עם מושגים פשוטים כמו ממוצע ומרחק. בוא נלמד את השפה שלהם.",
        readTime: "5 דקות",
        color: "sky",
        colorFrom: "from-sky-400",
        colorTo: "to-blue-500"
    },
    {
        id: 1,
        href: "/chapter-1",
        num: "פרק 1",
        label: "הבסיס: מתמטיקה", 
        title: "למה מתמטיקה היא חלק מהעבודה?",
        description: "בתוך המודל – כל זה נעלם. לא נשארת שפה, לא נשארת תמונה... הכול מתורגם למספרים.",
        readTime: "8 דקות",
        color: "blue",
        colorFrom: "from-blue-400",
        colorTo: "to-indigo-500"
    },
    {
        id: 2,
        href: "/chapter-2",
        num: "פרק 2",
        label: "סטטיסטיקה",
        title: "ממוצע, חציון וסטיית תקן – בלי סיבוכים",
        description: "איך מבינים את ה'מרכז' וה'פיזור' של הדאטה כדי לזהות רעש ואנומליות.",
        readTime: "10 דקות",
        color: "emerald",
        colorFrom: "from-emerald-400",
        colorTo: "to-green-500"
    },
    {
        id: 3,
        href: "/chapter-3",
        num: "פרק 3",
        label: "הסתברות למתכנתים",
        title: "הסתברות שמדברת בשפה של מתכנת",
        description: "הסתברות היא לא קסם, היא תדירות. איך מייצגים תרחישים וסיווגים בצורה פשוטה.",
        readTime: "12 דקות",
        color: "purple",
        colorFrom: "from-purple-400",
        colorTo: "to-fuchsia-500"
    },
    {
        id: 4,
        href: "/chapter-4",
        num: "פרק 4",
        label: "בייס והתניה",
        title: "הסתברות מותנית ובייס – הגרסה האנושית",
        description: "מה מסתתר מאחורי השאלה 'כמה סביר שזה נכון?' ואיך הקשר משנה את התמונה.",
        readTime: "10 דקות",
        color: "amber",
        colorFrom: "from-amber-400",
        colorTo: "to-yellow-500"
    },
    {
        id: 5,
        href: "/chapter-5",
        num: "פרק 5",
        label: "וקטורים ב-AI",
        title: "וקטורים – הלב של כל מודל",
        description: "איך טקסט, תמונה או משתמש הופכים לרשימת מספרים שהמחשב יודע לעבד.",
        readTime: "10 דקות",
        color: "indigo",
        colorFrom: "from-indigo-400",
        colorTo: "to-blue-700"
    },
    {
        id: 6,
        href: "/chapter-6",
        num: "פרק 6",
        label: "נורמה ומרחק",
        title: "נורמה ומרחק – מודדים את העולם",
        description: "מה זה 'אורך' של וקטור ואיך מודלים מודדים כמה דברים שונים זה מזה.",
        readTime: "12 דקות",
        color: "pink",
        colorFrom: "from-pink-400",
        colorTo: "to-rose-500"
    },
    {
        id: 7,
        href: "/chapter-7",
        num: "פרק 7",
        label: "דמיון קוסינוס",
        title: "זווית ודמיון קוסינוס",
        description: "למה בטקסט הכיוון חשוב יותר מהמרחק? על דמיון סמנטי ו-Embeddings.",
        readTime: "10 דקות",
        color: "rose",
        colorFrom: "from-rose-400",
        colorTo: "to-pink-500"
    },
    {
        id: 8,
        href: "/chapter-8",
        num: "פרק 8",
        label: "פונקציות ועקומות",
        title: "פונקציות – איך מודל חושב",
        description: "מה זו 'עקומה' ולמה כל מודל בעולם מנסה למצוא את המינימום שלה.",
        readTime: "8 דקות",
        color: "cyan",
        colorFrom: "from-cyan-400",
        colorTo: "to-sky-500"
    },
    {
        id: 9,
        href: "/chapter-9",
        num: "פרק 9",
        label: "שיפוע (Slope)",
        title: "שיפוע – המנוע של הלמידה",
        description: "מה זה שיפוע בלי להגיד 'נגזרת', ואיך הוא אומר למודל כמה טעות יש לו.",
        readTime: "10 דקות",
        color: "teal",
        colorFrom: "from-teal-400",
        colorTo: "to-emerald-500"
    },
    {
        id: 10,
        href: "/chapter-10",
        num: "פרק 10",
        label: "Gradient Descent",
        title: "Gradient Descent – הלמידה עצמה",
        description: "האלגוריתם שמניע את הכל: איך המודל גולש במורד העקומה כדי להקטין את הטעות.",
        readTime: "15 דקות",
        color: "fill-cyan-400",
        colorFrom: "from-cyan-400",
        colorTo: "to-blue-400"
    },
    {
        id: 11,
        href: "/chapter-11",
        num: "פרק 11",
        label: "פרויקט סיום",
        title: "פרויקט סיום – mini_math_primer",
        description: "כותבים קוד! יישום מעשי בפייתון של כל מה שלמדנו: ממוצע, בייס, נורמה ו-Gradient Descent.",
        readTime: "20 דקות",
        color: "orange",
        colorFrom: "from-orange-400",
        colorTo: "to-amber-500"
    },
    {
        id: 12,
        href: "/chapter-12",
        num: "פרק 12",
        label: "סיכום וחיבור ל-ML",
        title: "איך כל זה מתחבר ל-ML ול-NLP",
        description: "איך אבני הבניין שלמדנו (וקטורים, שיפועים, הסתברות) בונים את המודלים הגדולים ביותר.",
        readTime: "8 דקות",
        color: "slate",
        colorFrom: "from-slate-400",
        colorTo: "to-gray-500"
    }
];